# myvalues.yaml

infisical:
  replicaCount: 1

  kubeSecretRef: "infisical-auth-secrets"

  service:
    type: ClusterIP

  resources:
    limits:
      memory: 1000Mi
      cpu: "500m"
    requests:
      memory: 512Mi
      cpu: "250m"

ingress:
  enabled: true
  ingressClassName: traefik
  hostName: "infisical.jay-gemini.com"

  nginx:
    enabled: false

  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: web

# 외부 PostgreSQL을 사용하므로 내장 DB 설치를 끕니다.
postgresql:
  enabled: false

redis:
  enabled: true
  architecture: standalone
  auth:
    password: "your-redis-password"
