helm:
  parameters:
  - name: envName
    value: prod
    forcestring: false
  - name: imageUpdater.repository
    value: harbor.jaystacks.com/jay-blog-be
    forcestring: true
  - name: image.tag
    value: latest@sha256:f10f75670a99b0fd95f696aff4f38b5644cbc1b355a595d70d27c4c57fcc846a
    forcestring: true
