helm:
  parameters:
  - name: envName
    value: prod
    forcestring: false
  - name: imageUpdater.repository
    value: harbor.jaystacks.com/jay-blog-be
    forcestring: true
  - name: image.tag
    value: latest@sha256:a31c19ac853df8201fc7c2971d4d0403bdf625ca3c468081067a1c945a5c1372
    forcestring: true
