helm:
  parameters:
  - name: envName
    value: prod
    forcestring: false
  - name: imageUpdater.repository
    value: harbor.jaystacks.com/jay-blog-be
    forcestring: true
  - name: image.tag
    value: latest@sha256:0a9470e8d58db2ace4a1391aeba53d5ca19db28cdeb7e9a995498eaba51f5519
    forcestring: true
