destinationNamespace: monitoring

grafanaDashboards:
  enabled: true
  items:
    - name: legacy-nginx-web-analytics
      file: fgc-nginx01-web-analytics.json
    - name: legacy-nginx-traffic-map
      file: nginx-traffic-map.json
      folder: Infrastructure
    - name: legacy-node-exporter-full
      file: rYdddlPWk.json

prometheusRules:
  enabled: true
  labels:
    monitoring_jay_gemini_com_enabled: "true"
