replicaCount: 2

ingress:
  enabled: true
  className: traefik
  annotations: {}
  hosts:
    - host: minoooo119.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 1
    memory: 1Gi
