apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-dev-pvc
spec:
  storageClassName: jenkins-dev-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      type: local
