replicaCount: 1

image:
  repository: jmangel3404/sunsun-fe
  pullPolicy: Always # latest 태그를 쓰므로 항상 새로 받아오도록 설정
  tag: "latest"

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  className: "traefik" # k3s 기본인 traefik
  hosts:
    - host: sunsun.jay-gemini.com
      paths:
        - path: /
          pathType: ImplementationSpecific

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

# 환경 변수 설정 (필요 시)
env:
  NEXT_PUBLIC_API_URL: "https://sunsun-api.jay-gemini.com"
