replicaCount: 1

image:
  repository: harbor.jay-gemini.com/library/sunsun-be
  tag: "latest"
  pullPolicy: Always

# Private Repo 권한 (FE와 동일한 시크릿 사용)
imagePullSecrets:
  - name: harbor-creds

ingress:
  enabled: true
  className: "traefik"
  hosts:
    - host: sunsun-api.jay-gemini.com
      paths:
        - path: /
          pathType: ImplementationSpecific

service:
  type: ClusterIP
  port: 8080

imageUpdater:
  enabled: true
  updateStrategy: digest
  writeBackMethod: argocd

# [중요] DB 및 환경 설정
env:
  SPRING_PROFILES_ACTIVE: "prod"
  # K3s 내부 서비스 이름을 사용하여 DB 접속 (예: postgres-service)
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgresql-dev-primary.data.svc.cluster.local:5432/sunsun_db"
  SPRING_DATASOURCE_USERNAME: "sunsun_user"
  # 비밀번호는 직접 적지 말고 Secret에서 가져오는 것을 권장 (아래 가이드 참고)

resources:
  limits:
    memory: "768Mi"
    cpu: "500m"
  requests:
    memory: "512Mi"
    cpu: "256m"

  helm upgrade --install argocd ./bootstrap/argo-cd/chart -n server --create-namespace -f ./bootstrap/argo-cd/values/dev-values.yaml --dependency-update
  helm upgrade --install argocd argo/argo-cd -n server --create-namespace -f ./bootstrap/argo-cd/values/dev-values.yaml --version 9.2.3