fullnameOverride: "jenkins"
controller:
  admin:
    username: "firebat"
    password: "Firebat2030!"
  javaOpts: "-Dorg.apache.commons.jelly.tags.fmt.timeZone=Asia/Seoul -Duser.timezone=Asia/Seoul"
  installPlugins:
    - kubernetes:4423.vb_59f230b_ce53
    - workflow-aggregator:608.v67378e9d3db_1
    - git:5.9.0
    - configuration-as-code:2037.v8e5349845172
    - github:1.47.0
  installLatestPlugins: false
  installLatestSpecifiedPlugins: false
  initializeOnce: true
  JCasC:
    defaultConfig: true
    configScripts:
      kaniko-agent: |
        jenkins:
          clouds:
            - kubernetes:
                name: "kubernetes"
                serverUrl: "https://kubernetes.default.svc.cluster.local"
                skipTlsVerify: true
                namespace: "server"  # Jenkins가 설치된 네임스페이스
                templates:
                  - name: "kaniko"
                    label: "kaniko-agent"  # 파이프라인에서 'node("kaniko")'로 호출할 라벨
                    remoteFs: "/home/jenkins"
                    nodeUsageMode: "EXCLUSIVE"
                    containers:
                      - name: "kaniko"
                        image: "gcr.io/kaniko-project/executor:debug"
                        command: "/busybox/cat"
                        args: ""
                        ttyEnabled: true
                        privileged: false
                        alwaysPullImage: true

persistence:
  existingClaim: jenkins-pvc
