chartConfig:
  repoURL: https://helm.otwld.com/
  chart: ollama
  targetRevision: 1.41.0

ollama:
  gpu:
    enabled: false

  models:
    # 커스텀 모델 생성이 아니므로 비워둡니다.
    create: []

    # 컨테이너 시작 시 다운로드(Pull)할 모델 목록입니다.
    pull:
      - qwen2.5-coder:3b

    # 컨테이너 시작 시 메모리에 즉시 로드(Run)할 모델 목록입니다.
    run:
      - qwen2.5-coder:3b

    clean: false

persistentVolume:
  enabled: true
  size: 50Gi

resources:
  requests:
    cpu: "2"           # 최소 2코어 확보
    memory: "4Gi"      # 최소 4GB 램
  limits:
    memory: "24Gi"     # 32GB 중 다른 Pod를 위해 8GB 남기고 최대 24GB 할당

ingress:
  enabled: true
  hosts:
    - host: ollama.jay-gemini.com
      paths:
        - path: /
          pathType: Prefix