helm:
  parameters:
  - name: envName
    value: prod
    forcestring: false
  - name: imageUpdater.repository
    value: harbor.jaystacks.com/jay-blog-fe
    forcestring: true
  - name: image.tag
    value: latest@sha256:18dabe7b1368e73825dd77c94d2be045b4a579af37c46b51afbcc5b0524953ec
    forcestring: true
