helm:
  parameters:
  - name: envName
    value: prod
    forcestring: false
  - name: imageUpdater.repository
    value: harbor.jaystacks.com/jay-blog-fe
    forcestring: true
  - name: image.tag
    value: latest@sha256:c02aa464e1a78dbb94935272ddfa04e636b2bf6225b720e5830df6ddc56ab5f0
    forcestring: true
